version: "1.0.0"
services:
  react-app:
    image:react-app:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
      container_name: react-app
      restart: never
    ports:
      - 3000:3000
    networks:
      - react-app-network
networks:
  react-app-network:
    driver: bridge
